baseURL: "https://jsharkc.github.io/hugo-blog/"
title: Jacobc's blog
paginate: 10
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
# googleAnalytics: UA-123-45

outputs:
    home:
        - HTML
        - RSS
        - JSON

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Jacobc'S BLOG 
    description: "Jacobc's blog, welcome to my blog"
    keywords: [Blog, Portfolio, PaperMod, Jsharkc, golang]
    author: Jsharkc
    # author: ["Me", "You"] # multiple authors
    images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "January 2, 2006"
    defaultTheme: dark # auto, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: false
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: true
    hidemeta: false
    hideSummary: false
    showtoc: true
    tocopen: true

    assets:
        disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "<link / abs url>"
        favicon16x16: "<link / abs url>"
        favicon32x32: "<link / abs url>"
        apple_touch_icon: "<link / abs url>"
        safari_pinned_tab: "<link / abs url>"

  # label:
  #      text: "Home"
  #      icon: /apple-touch-icon.png
  #      iconHeight: 35

    # profile-mode
    profileMode:
        enabled: false # needs to be explicitly set
        title: ExampleSite
        subtitle: "This is subtitle"
        imageUrl: "<img location>"
        imageWidth: 120
        imageHeight: 120
        imageTitle: my image
        buttons:
            - name: Posts
              url: posts
            - name: Tags
              url: tags

    # home-info mode
    homeInfoParams:
        Title: "自律与自由"
        Content: >
            人在这个世界上是一定会被管理的
            
            - 区别在于：是别人管理，还是自己管理
              
            - 自己管理自己是自律，别人管理是奴役、管控、他律

            - 被别人管理当然是不自由的，所以你会发现：
        
            - 别人管理 + 自己管理 = 100%

            - 别人管理 = 他律 = 不自由

            - 自己管理 = 自律

            - 不自由 + 自律 = 100%

            - 自律 = 100% - 不自由 = 自由

            - 有多自律，就有多自由

    socialIcons:
        - name: github
          url: "https://github.com/Jsharkc"
        - name: RSS
          url: "index.xml"

    analytics:
        google:
            SiteVerificationTag: "XYZabc"
        bing:
            SiteVerificationTag: "XYZabc"
        yandex:
            SiteVerificationTag: "XYZabc"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    editPost:
        URL: "https://gitee.com/jsharkc/blog/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: archives
          name: Archives
          url: archives/
          weight: 5
        - identifier: categories
          name: Categories
          url: categories
          weight: 10
        - identifier: tags
          name: Tags
          url: tags
          weight: 20
        - identifier: search
          name: Search
          url: search
          weight: 30

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
    highlight:
        # anchorLineNos: true
        codeFences: true
        guessSyntax: true
        lineNos: true
        # noClasses: false
        style: monokai

